[package]
name = "plumage"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"
ron = "0.8"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[features]
panic = []
